/**
 * TypeScript types representing the YAML annotation schema
 * generated by the `sidenotes` Ruby gem.
 */

export interface ColumnInfo {
  name: string;
  type: string;
  nullable: boolean;
  default?: string | number | boolean | null;
  limit?: number;
  precision?: number;
  scale?: number;
  comment?: string;
}

export interface IndexInfo {
  name: string;
  columns: string[];
  unique: boolean;
  where?: string;
  using?: string;
  comment?: string;
}

export interface AssociationInfo {
  type: 'belongs_to' | 'has_one' | 'has_many' | 'has_and_belongs_to_many';
  name: string;
  class_name: string;
  foreign_key: string;
  through?: string;
  polymorphic?: boolean;
  dependent?: string;
}

export interface ModelAnnotation {
  table_name: string;
  primary_key: string;
  columns: ColumnInfo[];
  indexes: IndexInfo[];
  associations: AssociationInfo[];
}

/**
 * Lookup map: column name -> ColumnInfo for quick attribute resolution.
 */
export type ColumnMap = Map<string, ColumnInfo>;

/**
 * Build a ColumnMap from a ModelAnnotation for O(1) attribute lookups.
 */
export function buildColumnMap(annotation: ModelAnnotation): ColumnMap {
  const map: ColumnMap = new Map();
  for (const col of annotation.columns) {
    map.set(col.name, col);
  }
  return map;
}

/**
 * Format a column's type info as a concise inline string.
 * e.g. "string, not null" or "integer, nullable, default: 0"
 */
export function formatColumnInline(col: ColumnInfo): string {
  const parts: string[] = [col.type];
  if (col.nullable) {
    parts.push('nullable');
  } else {
    parts.push('not null');
  }
  if (col.default !== undefined && col.default !== null) {
    parts.push(`default: ${JSON.stringify(col.default)}`);
  }
  return parts.join(', ');
}
